version '3.8'

services:

  mariadb:
    image: mariadb                  #le nom de l'image
    container_name: mariadb         #le nom du container
    networks:
      - inception                   #a quel network il appartient
    build:
      context: requirements/mariadb #ou se trouve le Dockerfile
      dockerfile: Dockerfile        #le nom du Dockerfile
    env_file: .env                  #fichier d'environnement pour transmettre les variables
    volumes:
      - mariadb:/var/lib/mysql      
    restart: unless-stopped         
    expose:
      - "3306"                      #le port a exposer
    
  wordpress:
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: unless-stopped
    depends_on:
      - mariadb #wordpress demarrera  uniquement apres MariaDB (sinon il ne pourra pas configurer la base de donnees)
    expose:
      - "9000"
    
  nginx:
    image: nginx
    container_name: nginx
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "443:443"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind' #permet de faire le lien ntre volume du container et volume de l'hote
      device: '/home/lmelard/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/lmelard/data/db'

networks:
  inception:
    driver: bridge #reseau de pontage, mode de reseau Docker par defaut